BLK_INTV = 0.0001
#
# BOARD PIN CONF
LED  = '1'
TPIN = '2'
#
# DB Credentials
DB_USR = 'test_bot'
DB_PASS = 'password'
DB_HOST = 'localhost'
DB_DbName = 'TrainDb'
#
# SLEEP TIMES
TIME_SL_SURV = 5
TIME_SL_SPR = 1
# TWILLO
SID = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' 
AUTH_TOKEN = 'AAAAAAAAAAAAAAAAAAAAAAAAAA' 
FROM_NUMBER = '+111111111111'
